<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 02.06.2018
 * Time: 13:46
 */

namespace common\modules\catalog\widgets;

use yii\base\Widget;

class ProductCardWidget extends Widget {
    /** @var \common\modules\catalog\models\Product */
    public $model;
    
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }
    
    public function run() {
        parent::run(); // TODO: Change the autogenerated stub
    }
}